#!/usr/bin/env python3
"""Pack each recording folder in samples/ into one script file (samples/<set>.js).

Browsers won't let a page fetch() files when it is opened straight from disk
(file://), but they do run <script> files, so sampler.js loads these bundles.
Re-run after changing any MP3:  python3 tools/build_sample_bundles.py
"""
import base64, json, os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'samples')
manifest = json.load(open(os.path.join(ROOT, 'manifest.json')))
for name, info in manifest['sets'].items():
    notes = {}
    for n in info['notes']:
        with open(os.path.join(ROOT, name, n + '.mp3'), 'rb') as f:
            notes[n] = base64.b64encode(f.read()).decode('ascii')
    body = json.dumps({'gain': info.get('gain', 1), 'notes': notes}, separators=(',', ':'))
    out = os.path.join(ROOT, name + '.js')
    with open(out, 'w') as f:
        f.write('// Generated by tools/build_sample_bundles.py from samples/%s/*.mp3 '
                '(tonejs-instruments, CC BY 3.0; see samples/CREDITS.md)\n' % name)
        f.write('GuitarSamples.register(%s, %s);\n' % (json.dumps(name), body))
    print('%-16s %2d notes  %5.1f MB' % (name, len(notes), os.path.getsize(out) / 1e6))
